### ISSUE TITLE
データ型について

### ISSUE THREAD

**Issue by drinkBr** [nek009/key_event#1]
質問失礼いたします。

私はnek009様のコードを用いて入力したキーをmicro-rosを介して，ArduinoDueに渡してモータの制御を試みたいと考えています。しかし，micro-rosで渡せるデータ型には制限があり，投稿主様が用いているkey_event_msgs::msg::KeyEventはその対象外となっています。そこでgeometry_msgsのTwist型を用いてmicro-rosに対応したキー入力ノードを作成するにあたってどこを変更すればよいが教えていただきたいです。
この問題に1週間以上取り組んでいますが，解決できません。大きな問題としては
key_hit_event_node.hpp内にTwist型を宣言しても反応しないこと(CMakeLists.txtやpackage.xmlにgeometry_msgsは追加済み)
が挙げられます。
助言をよろしくお願いいたします。

https://github.com/micro-ROS/micro_ros_arduino

**Comment by nek009** [comment]
こんにちは．drinkBr様，
質問をありがとうございます．
結構前なのですが，使用していただけそうで嬉しいです．

さて，KeyEventメッセージの代わりにTwistの使用ということですね．
基本的にはkey_hit_event_node.hppの
7行目:Twist型に？
25行目:Twist型に
変更というところだと思います．
合わせて25行目の関数の実体はkey_hit_event_node.cpp.cppにありますが，こちらもTwist型に変更する必要があると思います．
とりあえずそのあたりだと思います．

**Comment by drinkBr** [comment]
nek009様

ご返信ありがとうございます。
該当箇所を変更し，colcon build --symlink-installでビルドしてみたところ，以下のエラーが発生しました。

key_hit_event_node.hpp:8:10: fatal error: geometry_msgs/msg/twist.hpp: No such file or directory
    8 | #include "geometry_msgs/msg/twist.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/serial_send_node.dir/build.make:76: CMakeFiles/serial_send_node.dir/src/serial_send_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/serial_send_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

このエラーについて調べましたが，その原因のほとんどはCMakeLists.txtやpackage.xmlへの記述の抜けというのがほとんどでした。そこで一つ質問なのですが，key_hit_event_nodeのCMakeLists.txtでament_target_dependenciesがコメントアウトされているのは何か意図があるのでしょうか？調べると書く場合が多いようだったので気になりました。

その後，tests/key_hit_event_target.cppを実行したところ，以下のエラー文が表示されてから，キーの送信が行われるようになってしまいました。

[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7413: open_and_lock_file failed -> Function open_port_internal

このエラーについて検索をかけましたが，同様の事例は見つかりませんでした。このエラーに関して何か経験ございましたら助言をお願いします。

また，ros2 topic info /key_hit_eventでデータ型を確認してみるとkey_event_msgs/msg/KeyEventのままでした。

助言よろしくお願いします。

**Comment by nek009** [comment]
こんにちは，drinkBr様，
確かにgeometry_msgs関係のエラーは設定ファイルへの記載漏れがメインっぽいですね．

それでament_target_dependenciesのコメントアウトについてです．
依存関係は，ament_target_dependenciesとament_export_dependenciesに記載しています(多分foxy以降だと自動判別してくれそうでいらないかもしれません)．
両方に同じものを書くのは良くないと思い，CMakeList.txtの24行目-28行目でまとめて書いています．
ここに書いて，ament_target_dependenciesやament_export_dependenciesに${key_hit_event_node_dependencies}と書くことで参照しています．
geometory_msg関係も24-28行目に書き，一方で27行目のkey_event_msgsの部分を削除するといけそうな気がします．

**Comment by drinkBr** [comment]
nek009様

ご返信ありがとうございます。
アドバイスを参考に検証を行った結果，ビルドした際のエラーについては同じワークスペース内にkey_hit_event_node.hppが複数存在していることによるものであると確認できました。
ありがとうございました。
しかし，以下に示すように新たなエラーが発生しました。

~/key_event/key_event_nodes/src/key_hit_event_node.cpp: In member function ‘void key_event::KeyHitEventNode::_pub_callback()’:
~/key_event/key_event_nodes/src/key_hit_event_node.cpp:44:10: error: ‘using element_type = struct geometry_msgs::msg::Twist_<std::allocator<void> >’ {aka ‘struct geometry_msgs::msg::Twist_<std::allocator<void> >’} has no member named ‘key’
   44 |     msg->key = getchar();
      |          ^~~
~/key_event/key_event_nodes/src/key_hit_event_node.cpp:46:10: error: ‘using element_type = struct geometry_msgs::msg::Twist_<std::allocator<void> >’ {aka ‘struct geometry_msgs::msg::Twist_<std::allocator<void> >’} has no member named ‘key’
   46 |     msg->key = '\0';
      |          ^~~
gmake[2]: *** [CMakeFiles/key_hit_event_node.dir/build.make:76: CMakeFiles/key_hit_event_node.dir/src/key_hit_event_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/key_hit_event_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

おそらくkey_event_msgs内で定義しているchar keyが使えなくなっていることによるエラーだと考えられますが，どのような変更の必要が考えられるでしょうか。

よろしくお願いします。

**Comment by nek009** [comment]
drinkBr様，
あー，確かにメッセージを使用しているところも変更しないといけませんね．
Twist型を使用した具体的な内容がわからないので(また残念ながらTwist型を使用したことがないので)，具体的な変数の使用方法・代入方法はわかりませんが，key_hit_event_node.cppの関係する部分をdrinkBr様の処理したいように書き換えれば動くと思います．
具体的には，

6行目: msgの定義．twist型に？
31行目:msgの定義．twist型に？
39行目:msgの定義．twist型に？
40-44行目:イベントを受け取った後の具体的な処理．twist型での処理に置き換え．
49-72行目:イベントを受け取った後の細かな処理．key_event_msgs用なので全部削除(40行目で読んでいる関数となっている)

ですね．

**Comment by drinkBr** [comment]
nek009様

返信遅くなってしまいすみません。投稿主様のご協力のおかげでString型でkey_eventを送信することが出来るようになりました。ありがとうございました。
また疑問が出た際にはよろしくお願いいたします。

**Comment by nek009** [comment]
よかった！動くようになって何よりです．
それでは一旦スレッドをしめさせてもらいますね．
頑張ってください．
